name: Main

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test:ci
